# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      ManagedBy = "Terragrunt"
      Project   = "platform-engineering"
    }
  }
}
